language: generic 

sudo: required 
services:
  - docker 

before_install: 
  - docker build -t augmart/docker-react -f Dockerfile.dev .  

scripts: 
  - docker run -e CI=true augmart/docker-react npm run test